version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - PUBLIC_API_URL=http://192.168.178.47:9091
    ports:
      - "9070:4321"  # Expose frontend to port 9070
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - app-network  

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "9091:80"  # Expose API on port 9091
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
    networks:
      - app-network  

volumes:
  gambling-db-data:
    driver: local

networks:
  app-network:
    driver: bridge
