version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - PUBLIC_API_URL=http://api:80
    ports:
      - "9070:4321"  # Expose frontend to port 9070
    environment:
      - NODE_ENV=production
      - PUBLIC_API_URL=http://api:80    
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - app-network  # Attach to the custom network

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "9091:80"  # Expose API on port 9091
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
    networks:
      - app-network  # Attach to the custom network

volumes:
  gambling-db-data:
    driver: local

networks:
  app-network:  # Define a custom network
    driver: bridge  # Use bridge driver for communication
