version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "9070:4321"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "9091:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped

volumes:
  gambling-db-data:
    driver: local