version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "9070:4321"  # Exposing frontend to port 9070
    environment:
      - NODE_ENV=production
      - API_URL=http://localhost:9091 
    restart: unless-stopped
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "9091:80"  # Exposing API on port 9091
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped

volumes:
  gambling-db-data:
    driver: local
